spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/react-admin?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: root
    password: 1234
mybatis:
  mapper-locations: classpath:mapping/*.xml

server:
  port: 5001

#Redis缓存配置
redis:
  #监察员模式开关
  usingSentinel: false
  # Redis数据库索引（默认为0）
  database: 0
  # Redis服务器地址
  host: 127.0.0.1
  # Redis服务器连接端口
  port: 6379
  # 连接超时时间（毫秒）
  timeout: 6000
  # 连接池最大连接数（使用负值表示没有限制）
  max-active: 50
  # 连接池中的最大空闲连接
  max-idle: 50
  # 连接池最大阻塞等待时间（使用负值表示没有限制）
  max-wait: 3000
  # 连接池中的最小空闲连接
  min-idle: 10


ftp:
  server:
    ip: 47.91.214.23
    http:
      prefix: 47.91.214.23/
  pass: ftpuser
  user: 12345678
  port: 21
