spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/react-admin?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: root
    password: 1234
  servlet:
      multipart:
          enabled: true
          max-file-size: 5MB
          max-request-size: 10MB
  mvc:
    view:
      prefix: /static/

mybatis:
  mapper-locations: classpath:mapping/*.xml

server:
  port: 5001

#Redis缓存配置
redis:
  #监察员模式开关
  usingSentinel: false
  # Redis数据库索引（默认为0）
  database: 0
  # Redis服务器地址
  host: 47.91.214.23
  # Redis服务器连接端口
  port: 6379
  # 连接超时时间（毫秒）
  timeout: 6000
  # 连接池最大连接数（使用负值表示没有限制）
  max-active: 50
  # 连接池中的最大空闲连接
  max-idle: 50
  # 连接池最大阻塞等待时间（使用负值表示没有限制）
  max-wait: 3000
  # 连接池中的最小空闲连接
  min-idle: 10


ftp:
  server:
    ip: 47.91.214.23
    http:
      prefix: 47.91.214.23/
  pass: 123456
  user: ftpuser
  port: 21
  path: /home/ftpuser/www/img/

local-file-store-path: D:\img\

pagehelper:
    ## pagehelper分页插件配置 ##
    #标识是哪一种数据库
    helperDialect: mysql
    #如果 pageSize=0 就会查询出全部的结果（相当于没有执行分页查询）
    page-size-zero: true
    #为了支持startPage(Object params)方法，增加了该参数来配置参数映射，用于从对象中根据属性名取值， 可以配置pageNum,pageSize,count,pageSizeZero,reasonable，不配置映射的用默认值， 默认值为pageNum=pageNum;pageSize=pageSize;count=countSql;reasonable=reasonable;pageSizeZero=pageSizeZero
    params: count=countSql
    # true启用合理化，如果pageNum<1会查询第一页，如果pageNum>pages会查询最后一页
    reasonable: false
    supportMethodsArguments: true

